### ISSUE TITLE
Implement evaluation scripts

### ISSUE THREAD

**Issue by dbogdanov** [multimediaeval/2019-Emotion-and-Theme-Recognition-in-Music-Task#4]
Proposed submission format (input): 
- NPY matrix (tracks x tags) with activation values
- NPY matrix (tracks x tags) with binary predictions (0 or 1)

Implement python scripts for the following metrics (see https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics)
- ROC-AUC and PR-AUC (averaged across tags) for activations matrix
- Micro- and macro-averaged precision, recall, and F-score for binary predictions.

Add the description of the submission format and scripts to the task README. We should provide the specification of the matrices (dimensions): number of tracks, number of tags, track IDs and track tags alphabetically sorted. 

The script should validate that the dimensions are correct.

**Comment by philtgun** [comment]
Closing as evaluation scripts have been implemented in [mtg-jamendo-dataset](https://github.com/MTG/mtg-jamendo-dataset) repository and added here in commit 2df3c99e9a7274b73046a38d546d380637f472dc
