### ISSUE TITLE
hello, i wanna know the project whether can output emtion and theme when i input some mp3?

### ISSUE THREAD

**Issue by bell-xiong** [multimediaeval/2019-Emotion-and-Theme-Recognition-in-Music-Task#7]
hello, i wanna know the project whether can output emotion and theme when i input some mp3s? or what is the project output and input,  i wanna use it to recognize emotion through BGM of video.

**Comment by philtgun** [comment]
This is a repository that contains information and submissions for a MediaEval challenge from 2019. If you want to use the models, please check out the individual submissions and their respective GitHub repositories. There are links to the team's repositories and papers on the [results page](https://multimediaeval.github.io/2019-Emotion-and-Theme-Recognition-in-Music-Task/results).
