### ISSUE TITLE
hello, how can I run these codes to predicted music mood or theme? 

### ISSUE THREAD

**Issue by bell-xiong** [multimediaeval/2019-Emotion-and-Theme-Recognition-in-Music-Task#8]

**Comment by dbogdanov** [comment]
Hi @bell-xiong, the script for the baseline and the pre-trained model are located at https://github.com/MTG/mtg-jamendo-dataset/tree/master/scripts/baseline. Therein, `main.py` contains an argument `--mode` that can be set to `TEST` for inference on the dataset. Are you referring to this script?

Besides, some of the participants in the challenge provide code for their models. Have a looks at the submissions for 2019, 2020 and 2021.

**Comment by philtgun** [comment]
In addition, you might want to take a look at the recently published auto-tagging architectures that achieve much better performance and have pre-trained models. 
For example: https://github.com/minzwon/semi-supervised-music-tagging-transformer

**Comment by bell-xiong** [comment]
Thank you so much for responding to my questions. However, I'm curious as to whether Direct can recognize emotion or theme from map3/wav files.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "multimediaeval/2019-Emotion-and-Theme-Recognition-in-Music-Task"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 晚上7:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [multimediaeval/2019-Emotion-and-Theme-Recognition-in-Music-Task] hello, how can I run these codes to predicted music mood or theme?  (Issue #8)





 
Hi @bell-xiong, the script for the baseline and the pre-trained model are located at https://github.com/MTG/mtg-jamendo-dataset/tree/master/scripts/baseline. Therein, main.py contains an argument --mode that can be set to TEST for inference on the dataset. Are you referring to this script?
 
Besides, some of the participants in the challenge provide code for their models. Have a looks at the submissions for 2019, 2020 and 2021.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
